name: Frist Workflow

on:
  push:
    branches:
    - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "welcome to our frist GitHub Actions WorkFlow! "

      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: List Repository File
        run: ls -la
